### PR TITLE
fix(icons): update status icons with new PF icons

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the status menu to use new icons from PatternFly

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-539-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-539-fabric8-runtime-console.badger.fabric8.io

**Comment by mindreeper2420** [comment]
blocked by https://github.com/fabric8-ui/fabric8-ui/pull/1824

**Comment by joshuawilson** [comment]
@mindreeper2420 I would think you would need to update the PF version here too.

**Comment by mindreeper2420** [comment]
@joshuawilson this still uses the `patternfly-sass-with-css` package that still uses version 3.21.2. Would it be better to close this and wait until this repo is moved?

**Comment by joshuawilson** [comment]
I'm working on the move now, so either I port this change over or you wait till it is moved. What changes with the status icons?

**Comment by mindreeper2420** [comment]
Lets wait until it is moved then. This changes the icons to use the new PatternFly ones for the various statuses, instead of a mix between Font Awesome and PatternFly. They all flow better between the different states, and have the same size/spacing.

**Comment by mindreeper2420** [comment]
I just noticed that this also changes other things, unintentionally. I'll close this.

**Pull request closed without merging**
