### PR TITLE
fix(duplicates): avoid duplicates on pipeline UI

### PR DESCRIPTION
**Pull request by jstrachan**
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1707

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-528-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-528-fabric8-runtime-console.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-528-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-528-fabric8-runtime-console.badger.fabric8.io

**Comment by joshuawilson** [comment]
This feels like a bandaid, it doesn't really clear up the duplicates, just hides them, right? What will happen when you get 1000 of them. Are they in OSO or just in the UI.

**Comment by jstrachan** [comment]
@joshuawilson this is all about properly merging websocket / poll events which are separate copies; this correctly merges them (there was a bug that was not merging identical resources)

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-528-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-528-fabric8-runtime-console.badger.fabric8.io

**Comment by jstrachan** [comment]
yay seems to work great - can't reproduce any dupes any more

**Pull request merged**
