### PR TITLE
fix(space): filter on space

### PR DESCRIPTION
**Pull request by jstrachan**
lets filter the apps on the space labels

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-496-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by jstrachan** [comment]
@fabric8cd CI downstream projects [fabric8-ui=jstrachan]

**Comment by jstrachan** [comment]
ok to test

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-496-fabric8-runtime-console.int.rdu2c.fabric8.io

**Pull request merged**
