### PR TITLE
fix: add the panel slide animation

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
[test]

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-204.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
It looks like ngx-widgets has no exported member 'SlideOutPanelModule'

**Comment by joshuawilson** [comment]
After reinstalling, I found that widgets is missing @types/core-js. So I fixed that and update runtime. So this PR should build after that.

**Pull request merged**
