### PR TITLE
WIP DONT MERGE fix(ci): enable snapshot deployments now we can chose …

### PR DESCRIPTION
**Pull request by rawlingsj**
…custom downstream projects

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-262.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-262.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-262.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-262.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-262.int.rdu2c.fabric8.io

**Comment by rawlingsj** [comment]
@fabric8cd CI downstream projects [fabric8-ui=rawlingsj]

**Pull request closed without merging**
