### PR TITLE
feat(apps page): adds a new apps page

### PR DESCRIPTION
**Pull request by jstrachan**
this new page shows a summary of all the apps in each environment, the version, numnber of pods and their states and the links to test out the apps in a single, simple view that folks can use to keep an eye on things #454

### CODE REVIEW

**Comment by jstrachan** [comment]
*NOTE* lets not merge until next week after the main demos are done

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by rawlingsj** [comment]
@fabric8cd CI downstream projects [fabric8-ui=jstrachan]

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-455-fabric8-runtime-console.int.rdu2c.fabric8.io

**Pull request merged**
