### PR TITLE
fix(status): add tenant status

### PR DESCRIPTION
**Pull request by jstrachan**
this PR adds a real time status view for jenkins + che

### CODE REVIEW

**Comment by jstrachan** [comment]
@fabric8cd CI downstream projects [fabric8-ui=jstrachan]

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by jstrachan** [comment]
the one downside of this PR is that fabric8-runtime-console can't know the entity (namespace) on the home page until the user clicks on a space. Am not sure of an easy way around that one until we move fabric8-runtime-console into fabric8-ui really. For now it just doesn't show tenant statuses until inside a space.

Also I was a tad nervous adding this widget onto app pages with its watching of spaces+jenkins/che. It would be nice if we could wrap this widget in some kind of lazy loading thingy so that its never used until folks actually display the drop down on the title bar

**Comment by jstrachan** [comment]
to test this out you can 

* open https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io 
* login
* go to the Space -> Create -> Pipeliness page
* open the openshift console in another window (via the top right kebab menu). 
* switch back to fabric8-ui and in any page within a space then open the status drop down
* now in the openshift console go to the -jenkins or -che windows and kill a pod; you should see the fabric8-ui status UI update in real time.
* you can also try the`Update Tenant` button - though make sure you realise often that button doesn not really do anything due to https://github.com/fabric8io/fabric8-init-tenant/issues/74

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by pmuir** [comment]
@jstrachan an ngIf should do that - `*ngIf="dropdownClicked"` for example (I think). Let me look at the code.

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io

**Pull request merged**
