### PR TITLE
fix(release): add CI pipeline stage to build and deploy PR changes into fabric8-ui and deploy it to test cluster

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at http://fabric8-ui-fabric8-ui-pr-168.int.rdu2c.fabric8.io

**Pull request merged**
