### PR TITLE
fix(status): update status widget with new designs

### PR DESCRIPTION
**Pull request by mindreeper2420**
Update the status widget with the new designs. Static content added until APIs are connected.

closes https://github.com/fabric8-ui/fabric8-ux/issues/522

### CODE REVIEW

**Comment by mindreeper2420** [comment]
**New Design:**
screen shot 2017-07-10 at 10 02 33 am

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-516-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-516-fabric8-runtime-console.badger.fabric8.io

**Comment by joshuawilson** [comment]
I tried the link by fabric8cd but it does not appear to have the changes.

**Comment by mindreeper2420** [comment]
@joshuawilson I don't think the fabric8cd is building the latest of anything - the home dashboard logo is also missing and the statuses are not updating (stuck on the hourglass icon).

**Pull request merged**
